# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: GithubHosts

on:
  push:
    branches:    
      - main
  schedule:
    - cron: '0 */2 * * *'
#   issues:
#     types: [opened] 

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements ]; then pip install -r requirements; fi
        
    - name: update hosts
      run: sh Hosts.sh && sh EpicHosts.sh && sh GithubHosts.sh && sh SteamDomains.sh
    - name: commit
      id: commit
      run: |
        git config --global user.email potterli520@gmail.com
        git config --global user.name action_bot
        git add .
        git commit -m "update hosts"
      continue-on-error: true
    - name: Check on failures
      if: steps.commit.outputs.status == 'failure'
      run: exit 1
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        
    # 删除无用 workflow runs;
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 0.1
        keep_minimum_runs: 1
        
